apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-sjzv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uzmp-tenant/quarkus/devfile-sample-code-with-quarkus-sjzv@sha256:16d14a673131928fa32905be6ec948e7160e91287a6822a7ccc0a4c0d0f9add9
        name: my-java-quarkus
        resources: {}
status: {}
